*** Variables ***

# General variables
${BROWSER}            Chrome
${URL}                https://panaryco.wixsite.com/myhotel?utm_source=chatgpt.com

# Input data
${FIRSTNAME}          John
${LASTNAME}           Smith
${PHONE}              123-456-7890
${EMAIL}              john.smith@example.com
${NUMBER_OF_ADULT}    2
${NOTE}               None

# Locators
${FNAME_BOX}                input_comp-lt33fcq41
${LNAME_BOX}                input_comp-lt33fcs1
${PHONE_BOX}                input_comp-lt33fcsi1
${EMAIL_BOX}                input_comp-lt33fcsf1

${NUMBER_OF_ADULT_BOX}      collection_comp-lt33fcsl1
${MENU_ITEM_BOX}            listModal_comp-lt33fcsl1
${MENU_ITEM}                menuitem-

${NOTE_BOX}                 input_comp-lt33fct3
${ACCEPT_CHECKBOX}          cCdhN7
${SUBMIT_BUTTON}            comp-lt33fctj